// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;
import {NacreRangeOffersForkTest, IState, ITestToken} from "./NacreRangeOffersFork.t.sol";
import {NacreLimitedOffer, NacreLimitedOfferFactory} from "../src/NacreLimitedOffers.sol";
import {NacrePolicyVault} from "../src/NacrePolicyVault.sol";
import {NacreAquaUnderwriter} from "../src/NacreAquaUnderwriter.sol";
contract NacreLimitedOffersForkTest is NacreRangeOffersForkTest {
    function testLimitedSpotsAtomicReservationsTopUpAndCompetingMakers() public {
        vm.createSelectFork(vm.envString("BASE_SEPOLIA_RPC_URL"));
        weth = 0x3333C20E21Eeaed85766232B20641d56fd3788c4;
        pool = 0x03be77c419a9a391c642576e5468d32ba21250f59d750be76e1043efe50c5a16;
        tradingFee = 10000;
        vault = NacrePolicyVault(0x879Ead283E76aFc12865CA43a0A3F10c3626CCe0);
        app = NacreAquaUnderwriter(0x0D2ED632E5A10aB713d183369687720d4e3817Cd);
        NacreLimitedOfferFactory factory = new NacreLimitedOfferFactory(app);
        (uint160 price,int24 tick,,) = IState(0x571291b572ed32ce6751a2Cb2486EbEe8DEfB9B4).getSlot0(pool);
        int24 lower = tick / 10 * 10 - 1000; int24 upper = tick / 10 * 10 + 1000;
        NacreLimitedOfferFactory.Bid[] memory bids = new NacreLimitedOfferFactory.Bid[](1);
        bids[0] = NacreLimitedOfferFactory.Bid(10000, 10e6, lower, upper, 7 days, 800, 1e6, 1);
        vm.startPrank(maker); ITestToken(address(token)).claim(); token.approve(address(factory), 10e6);
        NacreLimitedOffer offer = NacreLimitedOffer(factory.createOffers(bids)[0]); vm.stopPrank();
        uint256 token1 = _mint(price, lower, upper);
        vm.startPrank(lp); positions.approve(address(vault), token1);
        uint256 request1 = vault.createRequest(_key(), token1, 1e6, 1e6, 7 days, uint64(block.timestamp + 1 hours));
        offer.publish(request1); vm.stopPrank();
        assertEq(offer.availableSpots(), 0);
        assertEq(offer.unreservedCapital(), 9e6);
        address firstLp = lp; lp = address(0x4321);
        uint256 token2 = _mint(price, lower, upper);
        vm.startPrank(lp); positions.approve(address(vault), token2);
        uint256 request2 = vault.createRequest(_key(), token2, 1e6, 1e6, 7 days, uint64(block.timestamp + 1 hours));
        vm.expectRevert("No spots remaining"); offer.publish(request2); vm.stopPrank();
        vm.startPrank(maker); offer.setPremiumBps(900); token.approve(address(offer), 1e6); offer.topUp(1e6, 1); vm.stopPrank();
        assertEq(offer.availableSpots(), 1);
        assertEq(offer.quoteFor(request1).premium, 80000, "Published premium is locked");
        vm.startPrank(lp); offer.publish(request2); vm.stopPrank();
        assertEq(offer.quoteFor(request2).premium, 90000);
        NacreAquaUnderwriter.Quote memory stale = offer.quoteFor(request2);
        vm.warp(block.timestamp + 15 minutes + 1);
        assertEq(offer.availableSpots(), 2);
        vm.prank(lp); offer.publish(request2);
        assertEq(offer.availableSpots(), 1, "Renewal occupies exactly one slot");
        assertEq(offer.unreservedCapital(), 10e6, "Renewal reserves cap once");
        assertFalse(app.canFill(stale), "Expired strategy cannot fill reused slot");
        vm.prank(firstLp); offer.publish(request1);
        vm.startPrank(firstLp);
        NacreAquaUnderwriter.Quote memory q = offer.quoteFor(request1); token.approve(address(app), q.premium); app.buyCoverage(q); vm.stopPrank();
        assertEq(offer.availableSpots(), 0);
        vm.warp(block.timestamp + 15 minutes); assertEq(offer.availableSpots(), 0, "Not free AT expiry");
        vm.warp(block.timestamp + 1); assertEq(offer.availableSpots(), 1, "Expired unfilled reservation released");
        vm.prank(firstLp); vm.expectRevert("Only open offer owner"); offer.topUp(1e6, 1);
        vm.startPrank(address(0x7777)); ITestToken(address(token)).claim(); token.approve(address(factory), 10e6);
        NacreLimitedOffer competing = NacreLimitedOffer(factory.createOffers(bids)[0]); vm.stopPrank();
        assertEq(competing.tickLower(), offer.tickLower()); assertTrue(competing.owner() != offer.owner());
        lp = address(0x9999);
        uint256 token3 = _mint(price, lower, upper);
        vm.startPrank(lp); positions.approve(address(vault), token3);
        uint256 request3 = vault.createRequest(_key(), token3, 1e6, 1e6, 7 days, uint64(block.timestamp + 1 hours));
        offer.publish(request3); competing.publish(request3);
        NacreAquaUnderwriter.Quote memory losing = offer.quoteFor(request3);
        NacreAquaUnderwriter.Quote memory winning = competing.quoteFor(request3);
        vm.warp(winning.expiresAt);
        token.approve(address(app), winning.premium); app.buyCoverage(winning); vm.stopPrank();
        assertEq(offer.availableSpots(), 1, "Losing maker releases slot immediately");
        assertFalse(app.canFill(losing), "Cannot fill two makers for one request");
        assertEq(competing.availableSpots(), 0, "Exact-expiry purchase holds active slot");
        vm.prank(competing.owner()); competing.closeAndWithdraw();
        assertEq(token.balanceOf(address(competing)), 0);
        vm.warp(block.timestamp + 7 days); vault.settle(request3); vault.settle(request1);
        assertEq(offer.availableSpots(), 2);
        assertEq(token.balanceOf(address(competing)), 0, "Zero fees consume the full cap after closure");
    }
}
